### ISSUE TITLE
Packaging Bug, Wheel?

### ISSUE THREAD

**Issue by ghost** [juancarlospaco/dookumentation#16]
- https://dpaste.de/6Ki2

```
(doku)[angvp@minitardis][~]% pip install dookumentation             
Collecting dookumentation
  Downloading dookumentation-1.0.0.tar.bz2 (52kB)
    100% |████████████████████████████████| 53kB 194kB/s 
Requirement already satisfied (use --upgrade to upgrade): pip in ./virtualenvs/doku/lib/python3.5/site-packages (from dookumentation)
Building wheels for collected packages: dookumentation
  Running setup.py bdist_wheel for dookumentation
  Complete output from command /home/angvp/virtualenvs/doku/bin/python3.5 -c "import setuptools;__file__='/tmp/pip-build-_pn3mc_z/dookumentation/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpphxk7i27pip-wheel-:
  WARNING:root:Unix SysLog Server not found,ignored Logging to SysLog.
  Unix SysLog Server not found,ignored Logging to SysLog.
  running bdist_wheel
  running build
  running build_scripts
  creating build
  creating build/scripts-3.5
  copying and adjusting dookumentation.py -> build/scripts-3.5
  changing mode of build/scripts-3.5/dookumentation.py from 644 to 755
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_egg_info
  running egg_info
  writing dookumentation.egg-info/PKG-INFO
  writing top-level names to dookumentation.egg-info/top_level.txt
  writing requirements to dookumentation.egg-info/requires.txt
  writing dependency_links to dookumentation.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'dookumentation.egg-info/SOURCES.txt'
  writing manifest file 'dookumentation.egg-info/SOURCES.txt'
  Copying dookumentation.egg-info to build/bdist.linux-x86_64/wheel/dookumentation-1.0.0.data/purelib/dookumentation-1.0.0-py3.5.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/dookumentation-1.0.0.data/scripts
  copying build/scripts-3.5/dookumentation.py -> build/bdist.linux-x86_64/wheel/dookumentation-1.0.0.data/scripts
  changing mode of build/bdist.linux-x86_64/wheel/dookumentation-1.0.0.data/scripts/dookumentation.py to 755
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-_pn3mc_z/dookumentation/setup.py", line 265, in <module>
      'Topic :: Software Development',
    File "/usr/lib64/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib64/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib64/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/angvp/virtualenvs/doku/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/home/angvp/virtualenvs/doku/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/home/angvp/virtualenvs/doku/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError

  ----------------------------------------
  Failed building wheel for dookumentation
Failed to build dookumentation
Installing collected packages: dookumentation
  Running setup.py install for dookumentation
Successfully installed dookumentation-1.0.0
(doku)[angvp@minitardis][~]% 
```

**Comment by Kwpolska** [comment]
This is a wheel bug. Try `pip install --upgrade wheel` first.

**Comment by Kwpolska** [comment]
Also, unless you actually import `pip`, you should not have it in your dependencies.

**Comment by ghost** [comment]
Thanks @Kwpolska :exclamation: :smile_cat: 

Checking it right now seems to work...

**Comment by Kwpolska** [comment]
(close this issue if you _won’t fix_ it)

**Comment by ghost** [comment]
Closing, its working :smile_cat: 
**NotMyBug**
